@Content = new Meteor.SmartCollection "content"
@Games = new Meteor.SmartCollection "games"
@Movies = new Meteor.SmartCollection "videos"
@Shows = new Meteor.SmartCollection "shows"
@Posts = new Meteor.Collection "posts"